// <auto-generated />
using System;
using Banco;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PostoCombustivel.Migrations
{
    [DbContext(typeof(DataBase))]
    partial class DataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Bomba", b =>
                {
                    b.Property<int>("bombaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("limiteMaximo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("limiteMinimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("movimentacaoId")
                        .HasColumnType("int");

                    b.Property<int>("tipoCombustivelId")
                        .HasColumnType("int");

                    b.HasKey("bombaId");

                    b.HasIndex("movimentacaoId");

                    b.HasIndex("tipoCombustivelId");

                    b.ToTable("Bombas");
                });

            modelBuilder.Entity("Model.Combustivel", b =>
                {
                    b.Property<int>("combustivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("quantidadeEstoque")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("tipocombustivelId")
                        .HasColumnType("int");

                    b.HasKey("combustivelId");

                    b.HasIndex("tipocombustivelId");

                    b.ToTable("Combustiveis");
                });

            modelBuilder.Entity("Model.Fornecedor", b =>
                {
                    b.Property<int>("fornecedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("contato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("fornecedorId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("Model.Funcionario", b =>
                {
                    b.Property<int>("funcionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("funcao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("lojaId")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("funcionarioId");

                    b.HasIndex("lojaId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Model.Loja", b =>
                {
                    b.Property<int>("lojaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("lojaId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("Model.Movimentacao", b =>
                {
                    b.Property<int>("movimentacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("combustivelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("fornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("lojaId")
                        .HasColumnType("int");

                    b.Property<decimal>("quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("tipoOperacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("movimentacaoId");

                    b.HasIndex("combustivelId");

                    b.HasIndex("fornecedorId");

                    b.HasIndex("lojaId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("Model.TipoCombustivel", b =>
                {
                    b.Property<int>("tipoCombustivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCombustivel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("tipoCombustivelId");

                    b.ToTable("TiposCombustivel");
                });

            modelBuilder.Entity("Model.Bomba", b =>
                {
                    b.HasOne("Model.Movimentacao", "Movimentacao")
                        .WithMany()
                        .HasForeignKey("movimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.TipoCombustivel", "TipoCombustivel")
                        .WithMany()
                        .HasForeignKey("tipoCombustivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimentacao");

                    b.Navigation("TipoCombustivel");
                });

            modelBuilder.Entity("Model.Combustivel", b =>
                {
                    b.HasOne("Model.TipoCombustivel", "tipoCombustivel")
                        .WithMany()
                        .HasForeignKey("tipocombustivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipoCombustivel");
                });

            modelBuilder.Entity("Model.Funcionario", b =>
                {
                    b.HasOne("Model.Loja", "loja")
                        .WithMany()
                        .HasForeignKey("lojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("loja");
                });

            modelBuilder.Entity("Model.Movimentacao", b =>
                {
                    b.HasOne("Model.Combustivel", "Combustivel")
                        .WithMany()
                        .HasForeignKey("combustivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("fornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Loja", "Loja")
                        .WithMany()
                        .HasForeignKey("lojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combustivel");

                    b.Navigation("Fornecedor");

                    b.Navigation("Loja");
                });
#pragma warning restore 612, 618
        }
    }
}
